// frontend-angular/src/app/features/dashboard/teacher-dashboard/teacher-dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatChipsModule } from '@angular/material/chips';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { StatCardComponent } from '../../../shared/components/stat-card/stat-card.component';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';

@Component({
  selector: 'app-teacher-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    MatCardModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatTableModule,
    MatButtonModule,
    StatCardComponent,
    PageHeaderComponent,
  ],
  templateUrl: './teacher-dashboard.component.html',
  styleUrl: './teacher-dashboard.component.scss',
})
export class TeacherDashboardComponent {
  stats = {
    assignedClasses: 4,
    assignedStudents: 120,
    pendingAttendance: true,
    recentMessages: 3,
  };

  todaySchedule = [
    { periodNumber: 1, startTime: '08:00', endTime: '08:45', subjectName: 'Mathematics', className: 'Grade 10', sectionName: 'A', room: 'Room 101' },
    { periodNumber: 2, startTime: '08:45', endTime: '09:30', subjectName: 'Mathematics', className: 'Grade 9', sectionName: 'B', room: 'Room 102' },
    { periodNumber: 3, startTime: '09:45', endTime: '10:30', subjectName: 'Mathematics', className: 'Grade 10', sectionName: 'B', room: 'Room 101' },
    { periodNumber: 4, startTime: '10:30', endTime: '11:15', subjectName: 'Mathematics', className: 'Grade 8', sectionName: 'A', room: 'Room 103' },
    { periodNumber: 6, startTime: '12:00', endTime: '12:45', subjectName: 'Mathematics', className: 'Grade 9', sectionName: 'A', room: 'Room 102' },
  ];

  classesNeedingAttendance = [
    { className: 'Grade 10', sectionName: 'A', period: '1st Period' },
    { className: 'Grade 9', sectionName: 'B', period: '2nd Period' },
  ];

  upcomingExams = [
    { name: 'Mid-Term Test', class: 'Grade 10-A', date: '2024-03-15', subject: 'Mathematics' },
    { name: 'Unit Test 2', class: 'Grade 9-B', date: '2024-03-18', subject: 'Mathematics' },
  ];

  scheduleColumns = ['period', 'time', 'class', 'subject', 'room', 'attendance'];
}

<div class="teacher-dashboard">
  <app-page-header title="Teacher Dashboard"></app-page-header>

  <!-- Attendance Alert -->
  <div class="teacher-dashboard__alert" *ngIf="stats.pendingAttendance">
    <mat-icon>warning</mat-icon>
    <span>You have pending attendance for today. Please mark attendance for your classes.</span>
    <a mat-button routerLink="/attendance" class="teacher-dashboard__alert-action">Mark Now</a>
  </div>

  <!-- Stats Grid -->
  <div class="teacher-dashboard__stats">
    <app-stat-card
      title="My Classes"
      [value]="stats.assignedClasses"
      icon="class"
      color="primary"
    ></app-stat-card>
    <app-stat-card
      title="Total Students"
      [value]="stats.assignedStudents"
      icon="school"
      color="info"
    ></app-stat-card>
    <app-stat-card
      title="Today's Periods"
      [value]="todaySchedule.length"
      icon="schedule"
      color="success"
    ></app-stat-card>
    <app-stat-card
      title="Unread Messages"
      [value]="stats.recentMessages"
      icon="message"
      color="warning"
    ></app-stat-card>
  </div>

  <!-- Main Content -->
  <div class="teacher-dashboard__content">
    <!-- Today's Schedule -->
    <mat-card class="teacher-dashboard__schedule-card">
      <mat-card-header>
        <mat-icon mat-card-avatar class="teacher-dashboard__panel-icon">schedule</mat-icon>
        <mat-card-title>Today's Schedule</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <table mat-table [dataSource]="todaySchedule" class="teacher-dashboard__table">
          <ng-container matColumnDef="period">
            <th mat-header-cell *matHeaderCellDef>Period</th>
            <td mat-cell *matCellDef="let el">{{ el.periodNumber }}</td>
          </ng-container>
          <ng-container matColumnDef="time">
            <th mat-header-cell *matHeaderCellDef>Time</th>
            <td mat-cell *matCellDef="let el">{{ el.startTime }} - {{ el.endTime }}</td>
          </ng-container>
          <ng-container matColumnDef="class">
            <th mat-header-cell *matHeaderCellDef>Class</th>
            <td mat-cell *matCellDef="let el">{{ el.className }}-{{ el.sectionName }}</td>
          </ng-container>
          <ng-container matColumnDef="subject">
            <th mat-header-cell *matHeaderCellDef>Subject</th>
            <td mat-cell *matCellDef="let el">{{ el.subjectName }}</td>
          </ng-container>
          <ng-container matColumnDef="room">
            <th mat-header-cell *matHeaderCellDef>Room</th>
            <td mat-cell *matCellDef="let el">{{ el.room }}</td>
          </ng-container>
          <ng-container matColumnDef="attendance">
            <th mat-header-cell *matHeaderCellDef>Attendance</th>
            <td mat-cell *matCellDef="let el">
              <span class="teacher-dashboard__chip teacher-dashboard__chip--success">
                <mat-icon class="teacher-dashboard__chip-icon">check_circle</mat-icon>
                Marked
              </span>
            </td>
          </ng-container>
          <tr mat-header-row *matHeaderRowDef="scheduleColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: scheduleColumns;"></tr>
        </table>
      </mat-card-content>
    </mat-card>

    <!-- Sidebar -->
    <div class="teacher-dashboard__sidebar">
      <!-- Pending Attendance -->
      <mat-card class="teacher-dashboard__sidebar-card" *ngIf="classesNeedingAttendance.length > 0">
        <mat-card-header>
          <mat-icon mat-card-avatar class="teacher-dashboard__icon--warning">warning</mat-icon>
          <mat-card-title>Pending Attendance</mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list>
            <mat-list-item *ngFor="let cls of classesNeedingAttendance">
              <div class="teacher-dashboard__attendance-item">
                <div class="teacher-dashboard__item-avatar">
                  <mat-icon>event_note</mat-icon>
                </div>
                <div class="teacher-dashboard__item-info">
                  <span class="teacher-dashboard__item-title">{{ cls.className }}-{{ cls.sectionName }}</span>
                  <span class="teacher-dashboard__item-meta">{{ cls.period }}</span>
                </div>
                <a mat-flat-button color="primary" routerLink="/attendance" class="teacher-dashboard__mark-btn">
                  Mark
                </a>
              </div>
            </mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>

      <!-- Upcoming Exams -->
      <mat-card class="teacher-dashboard__sidebar-card">
        <mat-card-header>
          <mat-icon mat-card-avatar class="teacher-dashboard__panel-icon">assignment</mat-icon>
          <mat-card-title>Upcoming Exams</mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list>
            <mat-list-item *ngFor="let exam of upcomingExams">
              <div class="teacher-dashboard__list-item">
                <div class="teacher-dashboard__item-avatar">
                  <mat-icon>assignment</mat-icon>
                </div>
                <div class="teacher-dashboard__item-info">
                  <span class="teacher-dashboard__item-title">{{ exam.name }}</span>
                  <span class="teacher-dashboard__item-meta">{{ exam.class }} &bull; {{ exam.date }}</span>
                </div>
              </div>
            </mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</div>

// frontend/src/features/dashboard/pages/TeacherDashboard.tsx
import { Box, Grid, Card, CardContent, CardHeader, Typography, Chip, List, ListItem, ListItemText, ListItemIcon, Avatar, Alert, Button, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
import {
  Class as ClassIcon,
  EventNote as AttendanceIcon,
  Assignment as ExamIcon,
  Schedule as ScheduleIcon,
  Warning,
  CheckCircle,
  School as StudentIcon,
  Message as MessageIcon,
} from '@mui/icons-material';
import { StatCard } from '../../../components/common';
import { useGetTeacherDashboardQuery } from '../../../store/api/dashboardApi';
import { useGetTodayTimetableQuery } from '../../../store/api/dashboardApi';
import { Link as RouterLink } from 'react-router-dom';

export const TeacherDashboard = () => {
  const { data: dashboardData } = useGetTeacherDashboardQuery();
  const { data: timetableData } = useGetTodayTimetableQuery();

  const stats = dashboardData?.data || {
    assignedClasses: 4,
    assignedStudents: 120,
    pendingAttendance: true,
    upcomingExams: [],
    recentMessages: 3,
  };

  // Mock timetable data
  const todaySchedule = timetableData?.data || [
    { periodNumber: 1, startTime: '08:00', endTime: '08:45', subjectName: 'Mathematics', className: 'Grade 10', sectionName: 'A', room: 'Room 101' },
    { periodNumber: 2, startTime: '08:45', endTime: '09:30', subjectName: 'Mathematics', className: 'Grade 9', sectionName: 'B', room: 'Room 102' },
    { periodNumber: 3, startTime: '09:45', endTime: '10:30', subjectName: 'Mathematics', className: 'Grade 10', sectionName: 'B', room: 'Room 101' },
    { periodNumber: 4, startTime: '10:30', endTime: '11:15', subjectName: 'Mathematics', className: 'Grade 8', sectionName: 'A', room: 'Room 103' },
    { periodNumber: 6, startTime: '12:00', endTime: '12:45', subjectName: 'Mathematics', className: 'Grade 9', sectionName: 'A', room: 'Room 102' },
  ];

  const upcomingExams = [
    { name: 'Mid-Term Test', class: 'Grade 10-A', date: '2024-03-15', subject: 'Mathematics' },
    { name: 'Unit Test 2', class: 'Grade 9-B', date: '2024-03-18', subject: 'Mathematics' },
  ];

  const classesNeedingAttendance = [
    { className: 'Grade 10', sectionName: 'A', period: '1st Period' },
    { className: 'Grade 9', sectionName: 'B', period: '2nd Period' },
  ];

  return (
    <Box>
      <Typography variant="h5" fontWeight={600} sx={{ mb: 3 }}>
        Teacher Dashboard
      </Typography>

      {/* Attendance Alert */}
      {stats.pendingAttendance && (
        <Alert
          severity="warning"
          sx={{ mb: 3 }}
          action={
            <Button
              color="inherit"
              size="small"
              component={RouterLink}
              to="/attendance"
            >
              Mark Now
            </Button>
          }
        >
          You have pending attendance for today. Please mark attendance for your classes.
        </Alert>
      )}

      {/* Stats Grid */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="My Classes"
            value={stats.assignedClasses}
            icon={<ClassIcon />}
            color="primary"
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Total Students"
            value={stats.assignedStudents}
            icon={<StudentIcon />}
            color="info"
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Today's Periods"
            value={todaySchedule.length}
            icon={<ScheduleIcon />}
            color="success"
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Unread Messages"
            value={stats.recentMessages}
            icon={<MessageIcon />}
            color="warning"
          />
        </Grid>
      </Grid>

      {/* Main Content */}
      <Grid container spacing={3}>
        {/* Today's Timetable */}
        <Grid size={{ xs: 12, md: 8 }}>
          <Card>
            <CardHeader
              title="Today's Schedule"
              avatar={<ScheduleIcon color="primary" />}
            />
            <TableContainer>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Period</TableCell>
                    <TableCell>Time</TableCell>
                    <TableCell>Class</TableCell>
                    <TableCell>Subject</TableCell>
                    <TableCell>Room</TableCell>
                    <TableCell>Attendance</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {todaySchedule.map((period, index) => (
                    <TableRow key={index}>
                      <TableCell>{period.periodNumber}</TableCell>
                      <TableCell>{`${period.startTime} - ${period.endTime}`}</TableCell>
                      <TableCell>{`${period.className}-${period.sectionName}`}</TableCell>
                      <TableCell>{period.subjectName}</TableCell>
                      <TableCell>{period.room}</TableCell>
                      <TableCell>
                        <Chip
                          icon={<CheckCircle fontSize="small" />}
                          label="Marked"
                          size="small"
                          color="success"
                          variant="outlined"
                        />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </Card>
        </Grid>

        {/* Sidebar */}
        <Grid size={{ xs: 12, md: 4 }}>
          {/* Pending Attendance */}
          {classesNeedingAttendance.length > 0 && (
            <Card sx={{ mb: 3 }}>
              <CardHeader
                title="Pending Attendance"
                avatar={<Warning color="warning" />}
              />
              <List>
                {classesNeedingAttendance.map((cls, index) => (
                  <ListItem
                    key={index}
                    divider={index < classesNeedingAttendance.length - 1}
                    secondaryAction={
                      <Button
                        size="small"
                        variant="contained"
                        component={RouterLink}
                        to={`/attendance/mark?class=${cls.className}&section=${cls.sectionName}`}
                      >
                        Mark
                      </Button>
                    }
                  >
                    <ListItemIcon>
                      <Avatar sx={{ bgcolor: 'warning.light', width: 36, height: 36 }}>
                        <AttendanceIcon fontSize="small" />
                      </Avatar>
                    </ListItemIcon>
                    <ListItemText
                      primary={`${cls.className}-${cls.sectionName}`}
                      secondary={cls.period}
                    />
                  </ListItem>
                ))}
              </List>
            </Card>
          )}

          {/* Upcoming Exams */}
          <Card>
            <CardHeader
              title="Upcoming Exams"
              avatar={<ExamIcon color="primary" />}
              action={
                <Chip
                  label="View All"
                  size="small"
                  clickable
                  component="a"
                  href="/exams"
                />
              }
            />
            <List>
              {upcomingExams.map((exam, index) => (
                <ListItem key={index} divider={index < upcomingExams.length - 1}>
                  <ListItemIcon>
                    <Avatar sx={{ bgcolor: 'primary.light', width: 36, height: 36 }}>
                      <ExamIcon fontSize="small" />
                    </Avatar>
                  </ListItemIcon>
                  <ListItemText
                    primary={exam.name}
                    secondary={`${exam.class} • ${exam.date}`}
                  />
                </ListItem>
              ))}
            </List>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default TeacherDashboard;
