// frontend/src/features/dashboard/pages/ParentDashboard.tsx
import { Box, Grid, Card, CardContent, CardHeader, Typography, Chip, List, ListItem, ListItemText, ListItemIcon, Avatar, Select, MenuItem, FormControl, InputLabel, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Alert, Button } from '@mui/material';
import {
  EventNote as AttendanceIcon,
  Assignment as ExamIcon,
  Payment as FeeIcon,
  Event as EventIcon,
  Notifications as NotificationIcon,
  Person as ChildIcon,
  Warning,
  CheckCircle,
} from '@mui/icons-material';
import { useState } from 'react';
import { PieChart } from '@mui/x-charts/PieChart';
import { StatCard } from '../../../components/common';
import { useGetParentDashboardQuery } from '../../../store/api/dashboardApi';
import { Link as RouterLink } from 'react-router-dom';

export const ParentDashboard = () => {
  const [selectedChild, setSelectedChild] = useState('child1');
  const { data: dashboardData } = useGetParentDashboardQuery();

  // Mock children data
  const children = [
    { id: 'child1', name: 'Rahul Sharma', class: '10-A' },
    { id: 'child2', name: 'Priya Sharma', class: '8-B' },
  ];

  const stats = dashboardData?.data || {
    childAttendance: { percentage: 94.5, presentDays: 85, absentDays: 5, totalDays: 90 },
    recentMarks: [],
    feeStatus: { totalDue: 25000, totalPaid: 20000, outstanding: 5000 },
    schoolAnnouncements: [],
  };

  const recentMarks = [
    { exam: 'Mid-Term Math', marks: 45, total: 50, grade: 'A', date: '2024-03-10' },
    { exam: 'Science Quiz', marks: 18, total: 20, grade: 'A', date: '2024-03-08' },
    { exam: 'English Essay', marks: 38, total: 50, grade: 'B+', date: '2024-03-05' },
  ];

  const upcomingEvents = [
    { title: 'Parent-Teacher Meeting', date: '2024-03-16', type: 'ACADEMIC' },
    { title: 'Sports Day', date: '2024-03-22', type: 'SPORTS' },
    { title: 'Annual Function', date: '2024-03-28', type: 'CULTURAL' },
  ];

  const attendanceData = [
    { id: 0, value: 94.5, label: 'Present', color: '#4caf50' },
    { id: 1, value: 5.5, label: 'Absent', color: '#f44336' },
  ];

  const hasPendingFees = stats.feeStatus.outstanding > 0;

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h5" fontWeight={600}>
          Parent Dashboard
        </Typography>

        {/* Child Selector */}
        {children.length > 1 && (
          <FormControl size="small" sx={{ minWidth: 200 }}>
            <InputLabel>Select Child</InputLabel>
            <Select
              value={selectedChild}
              label="Select Child"
              onChange={(e) => setSelectedChild(e.target.value)}
            >
              {children.map((child) => (
                <MenuItem key={child.id} value={child.id}>
                  {child.name} ({child.class})
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        )}
      </Box>

      {/* Fee Alert */}
      {hasPendingFees && (
        <Alert
          severity="warning"
          sx={{ mb: 3 }}
          action={
            <Button
              color="inherit"
              size="small"
              component={RouterLink}
              to="/fee-status"
            >
              View Details
            </Button>
          }
        >
          You have pending fee dues of ₹{stats.feeStatus.outstanding.toLocaleString()}. Please clear them to avoid late fees.
        </Alert>
      )}

      {/* Stats Grid */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Child's Attendance"
            value={`${stats.childAttendance.percentage}%`}
            icon={<AttendanceIcon />}
            color={stats.childAttendance.percentage >= 75 ? 'success' : 'warning'}
            subtitle={`${stats.childAttendance.presentDays}/${stats.childAttendance.totalDays} days`}
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Fee Paid"
            value={`₹${(stats.feeStatus.totalPaid / 1000).toFixed(0)}K`}
            icon={<CheckCircle />}
            color="success"
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Fee Due"
            value={`₹${(stats.feeStatus.outstanding / 1000).toFixed(0)}K`}
            icon={<FeeIcon />}
            color={hasPendingFees ? 'warning' : 'success'}
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Notifications"
            value={5}
            icon={<NotificationIcon />}
            color="info"
          />
        </Grid>
      </Grid>

      {/* Main Content */}
      <Grid container spacing={3}>
        {/* Attendance Overview */}
        <Grid size={{ xs: 12, md: 4 }}>
          <Card sx={{ height: '100%' }}>
            <CardHeader title="Attendance Overview" />
            <CardContent>
              <Box sx={{ display: 'flex', justifyContent: 'center' }}>
                <PieChart
                  series={[
                    {
                      data: attendanceData,
                      innerRadius: 50,
                      outerRadius: 80,
                      paddingAngle: 2,
                      cornerRadius: 4,
                    },
                  ]}
                  height={180}
                  width={200}
                                  />
              </Box>
              <Box sx={{ mt: 2 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body2">Present Days</Typography>
                  <Typography variant="body2" fontWeight={600} color="success.main">
                    {stats.childAttendance.presentDays}
                  </Typography>
                </Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body2">Absent Days</Typography>
                  <Typography variant="body2" fontWeight={600} color="error.main">
                    {stats.childAttendance.absentDays}
                  </Typography>
                </Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Typography variant="body2">Total School Days</Typography>
                  <Typography variant="body2" fontWeight={600}>
                    {stats.childAttendance.totalDays}
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        {/* Recent Marks */}
        <Grid size={{ xs: 12, md: 8 }}>
          <Card>
            <CardHeader
              title="Recent Exam Marks"
              avatar={<ExamIcon color="primary" />}
              action={
                <Chip
                  label="View All"
                  size="small"
                  clickable
                  component="a"
                  href="/child-marks"
                />
              }
            />
            <TableContainer>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Exam</TableCell>
                    <TableCell>Date</TableCell>
                    <TableCell align="center">Marks</TableCell>
                    <TableCell align="center">Grade</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {recentMarks.map((exam, index) => (
                    <TableRow key={index}>
                      <TableCell>{exam.exam}</TableCell>
                      <TableCell>{exam.date}</TableCell>
                      <TableCell align="center">{`${exam.marks}/${exam.total}`}</TableCell>
                      <TableCell align="center">
                        <Chip
                          label={exam.grade}
                          size="small"
                          color={exam.grade.startsWith('A') ? 'success' : 'primary'}
                        />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </Card>
        </Grid>

        {/* Upcoming Events */}
        <Grid size={{ xs: 12, md: 6 }}>
          <Card>
            <CardHeader
              title="Upcoming Events"
              avatar={<EventIcon color="secondary" />}
            />
            <List>
              {upcomingEvents.map((event, index) => (
                <ListItem key={index} divider={index < upcomingEvents.length - 1}>
                  <ListItemIcon>
                    <Avatar sx={{ bgcolor: 'secondary.light', width: 36, height: 36 }}>
                      <EventIcon fontSize="small" />
                    </Avatar>
                  </ListItemIcon>
                  <ListItemText
                    primary={event.title}
                    secondary={event.date}
                  />
                  <Chip label={event.type} size="small" variant="outlined" />
                </ListItem>
              ))}
            </List>
          </Card>
        </Grid>

        {/* Fee Summary */}
        <Grid size={{ xs: 12, md: 6 }}>
          <Card>
            <CardHeader
              title="Fee Summary"
              avatar={<FeeIcon color="warning" />}
              action={
                <Chip
                  label="View Details"
                  size="small"
                  clickable
                  component="a"
                  href="/fee-status"
                />
              }
            />
            <CardContent>
              <Box sx={{ mb: 2 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body1">Total Due</Typography>
                  <Typography variant="body1" fontWeight={600}>
                    ₹{stats.feeStatus.totalDue.toLocaleString()}
                  </Typography>
                </Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body1" color="success.main">Paid</Typography>
                  <Typography variant="body1" fontWeight={600} color="success.main">
                    ₹{stats.feeStatus.totalPaid.toLocaleString()}
                  </Typography>
                </Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Typography variant="body1" color="error.main">Outstanding</Typography>
                  <Typography variant="body1" fontWeight={600} color="error.main">
                    ₹{stats.feeStatus.outstanding.toLocaleString()}
                  </Typography>
                </Box>
              </Box>
              {hasPendingFees && (
                <Button
                  variant="contained"
                  fullWidth
                  component={RouterLink}
                  to="/fee-status"
                >
                  Pay Now
                </Button>
              )}
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default ParentDashboard;

// frontend-angular/src/app/features/dashboard/parent-dashboard/parent-dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatChipsModule } from '@angular/material/chips';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { StatCardComponent } from '../../../shared/components/stat-card/stat-card.component';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';

@Component({
  selector: 'app-parent-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    FormsModule,
    MatCardModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatTableModule,
    MatButtonModule,
    MatSelectModule,
    MatFormFieldModule,
    StatCardComponent,
    PageHeaderComponent,
  ],
  templateUrl: './parent-dashboard.component.html',
  styleUrl: './parent-dashboard.component.scss',
})
export class ParentDashboardComponent {
  selectedChild = 'child1';

  children = [
    { id: 'child1', name: 'Rahul Sharma', class: '10-A' },
    { id: 'child2', name: 'Priya Sharma', class: '8-B' },
  ];

  stats = {
    childAttendance: { percentage: 94.5, presentDays: 85, absentDays: 5, totalDays: 90 },
    feeStatus: { totalDue: 25000, totalPaid: 20000, outstanding: 5000 },
  };

  recentMarks = [
    { exam: 'Mid-Term Math', marks: 45, total: 50, grade: 'A', date: '2024-03-10' },
    { exam: 'Science Quiz', marks: 18, total: 20, grade: 'A', date: '2024-03-08' },
    { exam: 'English Essay', marks: 38, total: 50, grade: 'B+', date: '2024-03-05' },
  ];

  upcomingEvents = [
    { title: 'Parent-Teacher Meeting', date: '2024-03-16', type: 'ACADEMIC' },
    { title: 'Sports Day', date: '2024-03-22', type: 'SPORTS' },
    { title: 'Annual Function', date: '2024-03-28', type: 'CULTURAL' },
  ];

  marksColumns = ['exam', 'date', 'marks', 'grade'];

  get hasPendingFees(): boolean {
    return this.stats.feeStatus.outstanding > 0;
  }

  isGradeA(grade: string): boolean {
    return grade.startsWith('A');
  }
}

<div class="parent-dashboard">
  <!-- Header with Child Selector -->
  <div class="parent-dashboard__header">
    <app-page-header title="Parent Dashboard"></app-page-header>
    <mat-form-field appearance="outline" class="parent-dashboard__child-select" *ngIf="children.length > 1">
      <mat-label>Select Child</mat-label>
      <mat-select [(ngModel)]="selectedChild">
        <mat-option *ngFor="let child of children" [value]="child.id">
          {{ child.name }} ({{ child.class }})
        </mat-option>
      </mat-select>
    </mat-form-field>
  </div>

  <!-- Fee Alert -->
  <div class="parent-dashboard__alert" *ngIf="hasPendingFees">
    <mat-icon>warning</mat-icon>
    <span>You have pending fee dues of {{ stats.feeStatus.outstanding | number }}. Please clear them to avoid late fees.</span>
    <a mat-button routerLink="/fee-status" class="parent-dashboard__alert-action">View Details</a>
  </div>

  <!-- Stats Grid -->
  <div class="parent-dashboard__stats">
    <app-stat-card
      title="Child's Attendance"
      [value]="stats.childAttendance.percentage + '%'"
      icon="event_note"
      [color]="stats.childAttendance.percentage >= 75 ? 'success' : 'warning'"
      [subtitle]="stats.childAttendance.presentDays + '/' + stats.childAttendance.totalDays + ' days'"
    ></app-stat-card>
    <app-stat-card
      title="Fee Paid"
      [value]="'$' + (stats.feeStatus.totalPaid / 1000).toFixed(0) + 'K'"
      icon="check_circle"
      color="success"
    ></app-stat-card>
    <app-stat-card
      title="Fee Due"
      [value]="'$' + (stats.feeStatus.outstanding / 1000).toFixed(0) + 'K'"
      icon="payment"
      [color]="hasPendingFees ? 'warning' : 'success'"
    ></app-stat-card>
    <app-stat-card
      title="Notifications"
      [value]="5"
      icon="notifications"
      color="info"
    ></app-stat-card>
  </div>

  <!-- Main Content -->
  <div class="parent-dashboard__content">
    <!-- Attendance Overview -->
    <mat-card class="parent-dashboard__panel">
      <mat-card-header>
        <mat-card-title>Attendance Overview</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div class="parent-dashboard__attendance-summary">
          <div class="parent-dashboard__attendance-row">
            <span>Present Days</span>
            <span class="parent-dashboard__value--success">{{ stats.childAttendance.presentDays }}</span>
          </div>
          <div class="parent-dashboard__attendance-row">
            <span>Absent Days</span>
            <span class="parent-dashboard__value--error">{{ stats.childAttendance.absentDays }}</span>
          </div>
          <div class="parent-dashboard__attendance-row">
            <span>Total School Days</span>
            <span class="parent-dashboard__value">{{ stats.childAttendance.totalDays }}</span>
          </div>
        </div>
      </mat-card-content>
    </mat-card>

    <!-- Recent Marks -->
    <mat-card class="parent-dashboard__panel parent-dashboard__panel--wide">
      <mat-card-header>
        <mat-icon mat-card-avatar class="parent-dashboard__panel-icon">assignment</mat-icon>
        <mat-card-title>Recent Exam Marks</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <table mat-table [dataSource]="recentMarks" class="parent-dashboard__table">
          <ng-container matColumnDef="exam">
            <th mat-header-cell *matHeaderCellDef>Exam</th>
            <td mat-cell *matCellDef="let el">{{ el.exam }}</td>
          </ng-container>
          <ng-container matColumnDef="date">
            <th mat-header-cell *matHeaderCellDef>Date</th>
            <td mat-cell *matCellDef="let el">{{ el.date }}</td>
          </ng-container>
          <ng-container matColumnDef="marks">
            <th mat-header-cell *matHeaderCellDef>Marks</th>
            <td mat-cell *matCellDef="let el">{{ el.marks }}/{{ el.total }}</td>
          </ng-container>
          <ng-container matColumnDef="grade">
            <th mat-header-cell *matHeaderCellDef>Grade</th>
            <td mat-cell *matCellDef="let el">
              <span
                class="parent-dashboard__chip"
                [ngClass]="isGradeA(el.grade) ? 'parent-dashboard__chip--success' : 'parent-dashboard__chip--primary'"
              >
                {{ el.grade }}
              </span>
            </td>
          </ng-container>
          <tr mat-header-row *matHeaderRowDef="marksColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: marksColumns;"></tr>
        </table>
      </mat-card-content>
    </mat-card>
  </div>

  <!-- Bottom Row -->
  <div class="parent-dashboard__bottom-row">
    <!-- Upcoming Events -->
    <mat-card class="parent-dashboard__panel">
      <mat-card-header>
        <mat-icon mat-card-avatar class="parent-dashboard__panel-icon--secondary">event</mat-icon>
        <mat-card-title>Upcoming Events</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <mat-list>
          <mat-list-item *ngFor="let event of upcomingEvents">
            <div class="parent-dashboard__list-item">
              <div class="parent-dashboard__item-avatar">
                <mat-icon>event</mat-icon>
              </div>
              <div class="parent-dashboard__item-info">
                <span class="parent-dashboard__item-title">{{ event.title }}</span>
                <span class="parent-dashboard__item-meta">{{ event.date }}</span>
              </div>
              <span class="parent-dashboard__item-badge">{{ event.type }}</span>
            </div>
          </mat-list-item>
        </mat-list>
      </mat-card-content>
    </mat-card>

    <!-- Fee Summary -->
    <mat-card class="parent-dashboard__panel">
      <mat-card-header>
        <mat-icon mat-card-avatar class="parent-dashboard__panel-icon--warning">payment</mat-icon>
        <mat-card-title>Fee Summary</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div class="parent-dashboard__fee-summary">
          <div class="parent-dashboard__fee-row">
            <span>Total Due</span>
            <span class="parent-dashboard__value">{{ stats.feeStatus.totalDue | number }}</span>
          </div>
          <div class="parent-dashboard__fee-row">
            <span class="parent-dashboard__value--success">Paid</span>
            <span class="parent-dashboard__value--success">{{ stats.feeStatus.totalPaid | number }}</span>
          </div>
          <div class="parent-dashboard__fee-row">
            <span class="parent-dashboard__value--error">Outstanding</span>
            <span class="parent-dashboard__value--error">{{ stats.feeStatus.outstanding | number }}</span>
          </div>
          <button
            mat-flat-button
            *ngIf="hasPendingFees"
            routerLink="/fee-status"
            class="parent-dashboard__pay-btn"
          >
            Pay Now
          </button>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
</div>
