// frontend/src/features/dashboard/pages/SuperAdminDashboard.tsx
import { Box, Grid, Card, CardContent, CardHeader, Typography, Chip, LinearProgress, Avatar, List, ListItem, ListItemAvatar, ListItemText } from '@mui/material';
import {
  Business as TenantIcon,
  People as PeopleIcon,
  School as SchoolIcon,
  Storage as StorageIcon,
  TrendingUp,
  CheckCircle,
  Warning,
  Block,
} from '@mui/icons-material';
import { PieChart } from '@mui/x-charts/PieChart';
import { BarChart } from '@mui/x-charts/BarChart';
import { StatCard } from '../../../components/common';
import { useGetGlobalStatsQuery, useGetTenantActivityQuery } from '../../../store/api/superAdminApi';

export const SuperAdminDashboard = () => {
  const { data: statsData, isLoading: statsLoading } = useGetGlobalStatsQuery();
  const { data: activityData } = useGetTenantActivityQuery({});

  const stats = statsData?.data;

  // Mock data for charts (will be replaced with real data)
  const tenantStatusData = [
    { id: 0, value: stats?.activeTenants || 45, label: 'Active', color: '#4caf50' },
    { id: 1, value: stats?.inactiveTenants || 8, label: 'Inactive', color: '#ff9800' },
    { id: 2, value: stats?.suspendedTenants || 2, label: 'Suspended', color: '#f44336' },
  ];

  const monthlyGrowthData = [
    { month: 'Jan', tenants: 35 },
    { month: 'Feb', tenants: 38 },
    { month: 'Mar', tenants: 42 },
    { month: 'Apr', tenants: 45 },
    { month: 'May', tenants: 50 },
    { month: 'Jun', tenants: 55 },
  ];

  const recentTenants = activityData?.data?.slice(0, 5) || [
    { tenantId: '1', schoolName: 'Greenwood Academy', lastLogin: '2 hours ago', activeUsers: 125 },
    { tenantId: '2', schoolName: 'St. Mary\'s School', lastLogin: '5 hours ago', activeUsers: 89 },
    { tenantId: '3', schoolName: 'Delhi Public School', lastLogin: '1 day ago', activeUsers: 210 },
    { tenantId: '4', schoolName: 'Cambridge International', lastLogin: '2 days ago', activeUsers: 156 },
    { tenantId: '5', schoolName: 'National Academy', lastLogin: '3 days ago', activeUsers: 78 },
  ];

  return (
    <Box>
      <Typography variant="h5" fontWeight={600} sx={{ mb: 3 }}>
        Super Admin Dashboard
      </Typography>

      {/* Stats Grid */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Total Tenants"
            value={stats?.totalTenants || 55}
            icon={<TenantIcon />}
            color="primary"
            trend={{ value: 12, label: 'vs last month' }}
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Total Users"
            value={(stats?.totalUsers || 15420).toLocaleString()}
            icon={<PeopleIcon />}
            color="info"
            trend={{ value: 8 }}
            subtitle="across all tenants"
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Total Students"
            value={(stats?.totalStudents || 12500).toLocaleString()}
            icon={<SchoolIcon />}
            color="success"
            trend={{ value: 5 }}
          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Storage Used"
            value={`${stats?.totalStorageUsedGb || 256} GB`}
            icon={<StorageIcon />}
            color="warning"
            subtitle="of 1 TB total"
          />
        </Grid>
      </Grid>

      {/* Charts Row */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 12, md: 4 }}>
          <Card sx={{ height: '100%' }}>
            <CardHeader title="Tenant Status" />
            <CardContent>
              <Box sx={{ display: 'flex', justifyContent: 'center' }}>
                <PieChart
                  series={[
                    {
                      data: tenantStatusData,
                      innerRadius: 50,
                      outerRadius: 90,
                      paddingAngle: 2,
                      cornerRadius: 4,
                      highlightScope: { fade: 'global', highlight: 'item' },
                    },
                  ]}
                  height={200}
                  width={250}
                                  />
              </Box>
              <Box sx={{ display: 'flex', justifyContent: 'center', gap: 2, mt: 2 }}>
                {tenantStatusData.map((item) => (
                  <Box key={item.label} sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                    <Box
                      sx={{
                        width: 12,
                        height: 12,
                        borderRadius: '50%',
                        bgcolor: item.color,
                      }}
                    />
                    <Typography variant="caption">
                      {item.label}: {item.value}
                    </Typography>
                  </Box>
                ))}
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid size={{ xs: 12, md: 8 }}>
          <Card sx={{ height: '100%' }}>
            <CardHeader title="Monthly Tenant Growth" />
            <CardContent>
              <BarChart
                xAxis={[{ scaleType: 'band', data: monthlyGrowthData.map((d) => d.month) }]}
                series={[{ data: monthlyGrowthData.map((d) => d.tenants), color: '#1976d2' }]}
                height={200}
              />
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Recent Activity & Quick Stats */}
      <Grid container spacing={3}>
        <Grid size={{ xs: 12, md: 6 }}>
          <Card>
            <CardHeader
              title="Recent Tenant Activity"
              action={
                <Chip
                  label="View All"
                  size="small"
                  clickable
                  component="a"
                  href="/superadmin/tenants"
                />
              }
            />
            <List>
              {recentTenants.map((tenant, index) => (
                <ListItem key={tenant.tenantId} divider={index < recentTenants.length - 1}>
                  <ListItemAvatar>
                    <Avatar sx={{ bgcolor: 'primary.main' }}>
                      {tenant.schoolName.charAt(0)}
                    </Avatar>
                  </ListItemAvatar>
                  <ListItemText
                    primary={tenant.schoolName}
                    secondary={`Last active: ${tenant.lastLogin}`}
                  />
                  <Chip
                    label={`${tenant.activeUsers} users`}
                    size="small"
                    variant="outlined"
                  />
                </ListItem>
              ))}
            </List>
          </Card>
        </Grid>

        <Grid size={{ xs: 12, md: 6 }}>
          <Card>
            <CardHeader title="System Health" />
            <CardContent>
              <Box sx={{ mb: 3 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body2">API Response Time</Typography>
                  <Typography variant="body2" fontWeight={600} color="success.main">
                    45ms avg
                  </Typography>
                </Box>
                <LinearProgress
                  variant="determinate"
                  value={85}
                  color="success"
                  sx={{ height: 8, borderRadius: 1 }}
                />
              </Box>

              <Box sx={{ mb: 3 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body2">Database Load</Typography>
                  <Typography variant="body2" fontWeight={600} color="warning.main">
                    62%
                  </Typography>
                </Box>
                <LinearProgress
                  variant="determinate"
                  value={62}
                  color="warning"
                  sx={{ height: 8, borderRadius: 1 }}
                />
              </Box>

              <Box sx={{ mb: 3 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body2">Storage Capacity</Typography>
                  <Typography variant="body2" fontWeight={600}>
                    256 GB / 1 TB
                  </Typography>
                </Box>
                <LinearProgress
                  variant="determinate"
                  value={25.6}
                  sx={{ height: 8, borderRadius: 1 }}
                />
              </Box>

              <Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="body2">Uptime</Typography>
                  <Typography variant="body2" fontWeight={600} color="success.main">
                    99.9%
                  </Typography>
                </Box>
                <LinearProgress
                  variant="determinate"
                  value={99.9}
                  color="success"
                  sx={{ height: 8, borderRadius: 1 }}
                />
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default SuperAdminDashboard;

// frontend-angular/src/app/features/dashboard/super-admin-dashboard/super-admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { StatCardComponent } from '../../../shared/components/stat-card/stat-card.component';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { ApiService } from '../../../core/services/api.service';

@Component({
  selector: 'app-super-admin-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatProgressBarModule,
    StatCardComponent,
    PageHeaderComponent,
  ],
  templateUrl: './super-admin-dashboard.component.html',
  styleUrl: './super-admin-dashboard.component.scss',
})
export class SuperAdminDashboardComponent implements OnInit {
  stats: any = {
    totalTenants: 0,
    activeTenants: 0,
    totalStudents: 0,
    totalUsers: 0,
    totalStorageUsedGb: 0,
    inactiveTenants: 0,
    suspendedTenants: 0,
  };

  recentTenants = [
    { tenantId: '1', schoolName: 'Greenwood Academy', lastLogin: '2 hours ago', activeUsers: 125 },
    { tenantId: '2', schoolName: "St. Mary's School", lastLogin: '5 hours ago', activeUsers: 89 },
    { tenantId: '3', schoolName: 'Delhi Public School', lastLogin: '1 day ago', activeUsers: 210 },
    { tenantId: '4', schoolName: 'Cambridge International', lastLogin: '2 days ago', activeUsers: 156 },
    { tenantId: '5', schoolName: 'National Academy', lastLogin: '3 days ago', activeUsers: 78 },
  ];

  systemHealth = [
    { label: 'API Response Time', value: '45ms avg', percentage: 85, color: 'success' },
    { label: 'Database Load', value: '62%', percentage: 62, color: 'warning' },
    { label: 'Storage Capacity', value: '256 GB / 1 TB', percentage: 25.6, color: 'primary' },
    { label: 'Uptime', value: '99.9%', percentage: 99.9, color: 'success' },
  ];

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.loadStats();
  }

  private loadStats(): void {
    this.apiService.getGlobalStats().subscribe({
      next: (res) => {
        if (res.success && res.data) {
          this.stats = { ...this.stats, ...res.data };
        }
      },
      error: () => {
        // Use default mock data
        this.stats = {
          totalTenants: 55,
          activeTenants: 45,
          totalStudents: 12500,
          totalUsers: 15420,
          totalStorageUsedGb: 256,
          inactiveTenants: 8,
          suspendedTenants: 2,
        };
      },
    });
  }

  getInitial(name: string): string {
    return name.charAt(0);
  }
}

<div class="super-admin-dashboard">
  <app-page-header title="Super Admin Dashboard"></app-page-header>

  <!-- Stats Grid -->
  <div class="super-admin-dashboard__stats">
    <app-stat-card
      title="Total Tenants"
      [value]="stats.totalTenants || 55"
      icon="business"
      color="primary"
      [trend]="{ value: 12, label: 'vs last month' }"
    ></app-stat-card>
    <app-stat-card
      title="Total Users"
      [value]="(stats.totalUsers || 15420).toLocaleString()"
      icon="people"
      color="info"
      [trend]="{ value: 8 }"
      subtitle="across all tenants"
    ></app-stat-card>
    <app-stat-card
      title="Total Students"
      [value]="(stats.totalStudents || 12500).toLocaleString()"
      icon="school"
      color="success"
      [trend]="{ value: 5 }"
    ></app-stat-card>
    <app-stat-card
      title="Storage Used"
      [value]="(stats.totalStorageUsedGb || 256) + ' GB'"
      icon="storage"
      color="warning"
      subtitle="of 1 TB total"
    ></app-stat-card>
  </div>

  <!-- Recent Activity & System Health -->
  <div class="super-admin-dashboard__panels">
    <!-- Recent Tenant Activity -->
    <mat-card class="super-admin-dashboard__panel">
      <mat-card-header>
        <mat-card-title>Recent Tenant Activity</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <mat-list>
          <mat-list-item *ngFor="let tenant of recentTenants; let last = last">
            <div class="super-admin-dashboard__tenant-item">
              <div class="super-admin-dashboard__tenant-avatar">
                {{ getInitial(tenant.schoolName) }}
              </div>
              <div class="super-admin-dashboard__tenant-info">
                <span class="super-admin-dashboard__tenant-name">{{ tenant.schoolName }}</span>
                <span class="super-admin-dashboard__tenant-meta">Last active: {{ tenant.lastLogin }}</span>
              </div>
              <span class="super-admin-dashboard__tenant-badge">{{ tenant.activeUsers }} users</span>
            </div>
          </mat-list-item>
        </mat-list>
      </mat-card-content>
    </mat-card>

    <!-- System Health -->
    <mat-card class="super-admin-dashboard__panel">
      <mat-card-header>
        <mat-card-title>System Health</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div class="super-admin-dashboard__health-items">
          <div
            class="super-admin-dashboard__health-item"
            *ngFor="let item of systemHealth"
          >
            <div class="super-admin-dashboard__health-header">
              <span class="super-admin-dashboard__health-label">{{ item.label }}</span>
              <span
                class="super-admin-dashboard__health-value"
                [ngClass]="'super-admin-dashboard__health-value--' + item.color"
              >
                {{ item.value }}
              </span>
            </div>
            <mat-progress-bar
              mode="determinate"
              [value]="item.percentage"
              [color]="item.color === 'success' ? 'primary' : item.color === 'warning' ? 'warn' : 'accent'"
            ></mat-progress-bar>
          </div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
</div>
